/*
 * AltaTitularFamiliarUI.java
 *
 * Created on 17-ene-2013, 10:50:46
 */
package miGPUI;

import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Profesor
 */
public class AltaPacientePrivadoUI extends javax.swing.JDialog {
   
    PacientePrivado pacientePrivadoADevolver = null;

    
    // Para devolver al JFrame principal el objeto paciente
    public PacientePrivado getPacientePrivado() {
        return pacientePrivadoADevolver ;    
    }

    /** Creates new form AltaPacientePrivadoUI */
    public AltaPacientePrivadoUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLNif = new javax.swing.JLabel();
        jLNombrePaciente = new javax.swing.JLabel();
        jLNumeroVisitas = new javax.swing.JLabel();
        jLTipoPago = new javax.swing.JLabel();
        jTFNif = new javax.swing.JTextField();
        jTFNombrePacientePrivado = new javax.swing.JTextField();
        jTFNumeroVisitas = new javax.swing.JTextField();
        jLAnnioPrimeraConsulta = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jTFAnnioPrimeraConsulta = new javax.swing.JTextField();
        jLEmailNotificacion = new javax.swing.JLabel();
        jTFEmailNotificacion = new javax.swing.JTextField();
        jCBTipoPago = new javax.swing.JComboBox();
        jLNumeroTratamientosPorFacturar = new javax.swing.JLabel();
        jTFNumeroTratamientosPorFacturar = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de un nuevo Paciente Privado");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alta de un nuevoPaciente Privado."));

        jLNif.setText("NIF:");

        jLNombrePaciente.setText("Nombre del Paciente:");

        jLNumeroVisitas.setText("Número de Visitas:");

        jLTipoPago.setText("Tipo de Pago:");

        jTFNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNifActionPerformed(evt);
            }
        });

        jTFNombrePacientePrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombrePacientePrivadoActionPerformed(evt);
            }
        });

        jTFNumeroVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroVisitasActionPerformed(evt);
            }
        });

        jLAnnioPrimeraConsulta.setText("Año de Primera Consulta:");

        jBGuardar.setMnemonic('G');
        jBGuardar.setText("Guardar");
        jBGuardar.setToolTipText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setMnemonic('C');
        jBCancelar.setText("Cancelar");
        jBCancelar.setToolTipText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jTFAnnioPrimeraConsulta.setText("2013");

        jLEmailNotificacion.setText("email Notificación:");

        jTFEmailNotificacion.setName("JTextFieldEmail"); // NOI18N
        jTFEmailNotificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailNotificacionActionPerformed(evt);
            }
        });

        jCBTipoPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Metalico", "Tarjeta" }));
        jCBTipoPago.setToolTipText("Tipo de Pago");

        jLNumeroTratamientosPorFacturar.setText("Número de Tratamientos por facturar:");

        jTFNumeroTratamientosPorFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroTratamientosPorFacturarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLNif, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNif, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLAnnioPrimeraConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFAnnioPrimeraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLNumeroVisitas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNumeroVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEmailNotificacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombrePaciente, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLNumeroTratamientosPorFacturar)
                        .addGap(26, 26, 26)
                        .addComponent(jTFNumeroTratamientosPorFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFEmailNotificacion)
                            .addComponent(jTFNombrePacientePrivado))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLTipoPago)
                                .addGap(34, 34, 34)
                                .addComponent(jCBTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBGuardar)
                                .addGap(29, 29, 29)
                                .addComponent(jBCancelar)))
                        .addGap(46, 46, 46))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNif)
                    .addComponent(jTFNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmailNotificacion)
                    .addComponent(jTFEmailNotificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombrePaciente)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLAnnioPrimeraConsulta)
                        .addComponent(jTFNombrePacientePrivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFAnnioPrimeraConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCBTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLTipoPago)
                        .addComponent(jLNumeroVisitas))
                    .addComponent(jTFNumeroVisitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroTratamientosPorFacturar)
                    .addComponent(jTFNumeroTratamientosPorFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBGuardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNifActionPerformed

    private void jTFNombrePacientePrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombrePacientePrivadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombrePacientePrivadoActionPerformed

    private void jTFNumeroVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroVisitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroVisitasActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        try{
            PacientePrivado.TipoDePago pago;
            if(jCBTipoPago.getSelectedIndex()==0){
                pago=PacientePrivado.TipoDePago.Metalico;
            }else{
                pago=PacientePrivado.TipoDePago.Tarjeta;
            }
            pacientePrivadoADevolver = new PacientePrivado(
                jTFNif.getText().toUpperCase(),
                Integer.parseInt(jTFAnnioPrimeraConsulta.getText()),
                jTFNombrePacientePrivado.getText(),
                Integer.parseInt(jTFNumeroTratamientosPorFacturar.getText()),    
                jTFEmailNotificacion.getText(),
                Integer.parseInt(jTFNumeroVisitas.getText()),
                pago);
           
            // Ocultar el formulario
            this.setVisible(false);

        }catch (NumberFormatException nfe){
            JOptionPane.showMessageDialog(null,"Error: Alguno de los campos numéricos \n"
                    + "(Año de primera consulta, Número tratamientos por facturar o Número de visitas)"
                    + " \n no contiene un número entero válido. \n", "Error", JOptionPane.ERROR_MESSAGE);
        }catch (IllegalArgumentException iae){
            JOptionPane.showMessageDialog(null,iae.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // Ocultar el formulario
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFEmailNotificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailNotificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailNotificacionActionPerformed

    private void jTFNumeroTratamientosPorFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroTratamientosPorFacturarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroTratamientosPorFacturarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JComboBox jCBTipoPago;
    private javax.swing.JLabel jLAnnioPrimeraConsulta;
    private javax.swing.JLabel jLEmailNotificacion;
    private javax.swing.JLabel jLNif;
    private javax.swing.JLabel jLNombrePaciente;
    private javax.swing.JLabel jLNumeroTratamientosPorFacturar;
    private javax.swing.JLabel jLNumeroVisitas;
    private javax.swing.JLabel jLTipoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFAnnioPrimeraConsulta;
    private javax.swing.JTextField jTFEmailNotificacion;
    private javax.swing.JTextField jTFNif;
    private javax.swing.JTextField jTFNombrePacientePrivado;
    private javax.swing.JTextField jTFNumeroTratamientosPorFacturar;
    private javax.swing.JTextField jTFNumeroVisitas;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
