
package miGPUI;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import sun.rmi.transport.proxy.CGIHandler;

/**
 *
 * @author Nar
 */
public class EnviarEmailUI extends javax.swing.JDialog {

    /**
     * Creates new form EnviarEmailUI
     */
    public EnviarEmailUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLEncabezadoVentana = new javax.swing.JLabel();
        jLAsunto = new javax.swing.JLabel();
        jTFAsunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAAreaTextoMensaje = new javax.swing.JTextArea();
        jLAreaTextoMensaje = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jTFUsuario = new javax.swing.JTextField();
        jLContrasenia = new javax.swing.JLabel();
        jPFContrasenia = new javax.swing.JPasswordField();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Envío de liquidaciones de facturación de pacientes");
        setAlwaysOnTop(true);

        jLEncabezadoVentana.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLEncabezadoVentana.setText("Envío de Liquidaciones del impuesto a todos los propietaros de vehículos.");

        jLAsunto.setText("Asunto: ");
        jLAsunto.setToolTipText("");

        jTFAsunto.setText("Mi Clínica: Facturación al paciente. ");
        jTFAsunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAsuntoActionPerformed(evt);
            }
        });

        jTAAreaTextoMensaje.setColumns(20);
        jTAAreaTextoMensaje.setRows(5);
        jScrollPane1.setViewportView(jTAAreaTextoMensaje);

        jLAreaTextoMensaje.setText("Texto del mensaje (admite etiquetas html):");

        jLUsuario.setText("Usuario: ");

        jTFUsuario.setText("miclinicadental@gmail.com");

        jLContrasenia.setText("Contraseña:");

        jBAceptar.setMnemonic('A');
        jBAceptar.setText("Aceptar");
        jBAceptar.setToolTipText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });

        jBCancelar.setMnemonic('C');
        jBCancelar.setText("Cancelar");
        jBCancelar.setToolTipText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLAsunto)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                                    .addComponent(jTFAsunto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLContrasenia)
                                            .addComponent(jLUsuario))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPFContrasenia)
                                            .addComponent(jTFUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addComponent(jBCancelar))
                            .addComponent(jLAreaTextoMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLEncabezadoVentana)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEncabezadoVentana)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAsunto)
                    .addComponent(jTFAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLAreaTextoMensaje)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContrasenia)
                    .addComponent(jPFContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAceptar)
                    .addComponent(jBCancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
       String asunto=jTFAsunto.getText();
       String textoMensaje=jTAAreaTextoMensaje.getText();
       String usuario=jTFUsuario.getText();
       String contrasenia= new String (jPFContrasenia.getPassword());
       Paciente miPaciente;
       boolean sinProblemasValidandoUsuario=true;
       Pattern mail=Pattern.compile("[^@]+[@]{1}[^@]+(.[a-z]{2,4}){1,2}");
       
       Matcher mMail=mail.matcher(usuario.toLowerCase());
       if (mMail.matches()){
           int tamanio=JFGestionFacturacionPacientesUI.getListaPacientes().size();
           for (int contador=0; contador<tamanio && sinProblemasValidandoUsuario;contador++ ){
             miPaciente=JFGestionFacturacionPacientesUI.getListaPacientes().get(contador);
             textoMensaje=jTAAreaTextoMensaje.getText(); //Para reiniciar el texto a enviar para cada envío de email
             textoMensaje+="\n\n"+miPaciente.toString();
             try{
                miPaciente.enviarleEmail(asunto, textoMensaje, usuario, contrasenia);
             }catch (MessagingException mex){
                 JOptionPane.showMessageDialog(null, mex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                 sinProblemasValidandoUsuario=false;
             }
           }
           if(sinProblemasValidandoUsuario){
                JOptionPane.showMessageDialog(null, "El envío de  las liquidaciones de Facturación a los pacientes  \n"
                        + " por email se ha completado con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE); 
             }
       }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
       // Ocultar el formulario
       this.setVisible(false);
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFAsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFAsuntoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JLabel jLAreaTextoMensaje;
    private javax.swing.JLabel jLAsunto;
    private javax.swing.JLabel jLContrasenia;
    private javax.swing.JLabel jLEncabezadoVentana;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JPasswordField jPFContrasenia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAAreaTextoMensaje;
    private javax.swing.JTextField jTFAsunto;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
