/*
 * ListarPersonasUI.java
 *
 * Created on 18-dic-2012, 10:46:37
 */
package miGPUI;

import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Profesor
 */
public class ListadoPacientesUI extends javax.swing.JDialog {

    private ArrayList <Paciente> laLista ;
    
    /** Crea formulario ListadoPacientesUI 
     * Constructor modificado para pasarle como tercer parámetro la lista de pacientes
    */
    public ListadoPacientesUI(java.awt.Frame parent, boolean modal, ArrayList <Paciente> listaPacientes ) {
        super(parent, modal);
        
        // Inicializar el formulario               
        initComponents();
        
        // Referencia a la lista para obtener el paciente
        laLista = listaPacientes ;  
        Collections.sort(laLista, new ComparadorNombrePaciente());
        int contador ;
        int tamano = listaPacientes.size() ;
        final String vector[] = new String[tamano];
        for (contador = 0; contador < tamano; contador++ ) {
             vector[contador] = laLista.get(contador).getNif() + " -- " + 
                    laLista.get(contador).getNombrePaciente()+" -- " + 
                    laLista.get(contador).getAntiguedad()+" -- " +
                    laLista.get(contador).getEmailNotificaciones()+  
                    String.format(" -- %.2f €.",laLista.get(contador).liquidarFacturacion());
        }
        
        
        jListListaPacientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vector ;  //{ "Prueba", "Item 2", "Item 3", "Item 4", "Item 5" };
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListListaPacientes.setSelectedIndex(0);
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOpcionesOrdenacion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListaPacientes = new javax.swing.JList();
        jBotonMostrar = new javax.swing.JButton();
        jLabelOrdenar = new javax.swing.JLabel();
        jRadioButtonPorNombrePacienteAscendente = new javax.swing.JRadioButton();
        jRadioButtonPorAntiguedad = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLTotalPacientes = new javax.swing.JLabel();
        jLNumeroPacientesPrivados = new javax.swing.JLabel();
        jTFTotalPacientes = new javax.swing.JTextField();
        jTFNumeroPacientesPrivados = new javax.swing.JTextField();
        jLNumeroPacientesSeguroMedico = new javax.swing.JLabel();
        jTF_NumeroPacientesSeguroMedico = new javax.swing.JTextField();
        jBotonCerrarListado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado de Pacientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pacientes (NIF -- Nombre del Paciente -- Antigüedad --  Email para norificación-- Liquidación de Facturación)"));

        jListListaPacientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(jListListaPacientes);

        jBotonMostrar.setMnemonic('V');
        jBotonMostrar.setText("Ver Información");
        jBotonMostrar.setToolTipText("Ver información");
        jBotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMostrarActionPerformed(evt);
            }
        });

        jLabelOrdenar.setText("Ordenar por:");

        buttonGroupOpcionesOrdenacion.add(jRadioButtonPorNombrePacienteAscendente);
        jRadioButtonPorNombrePacienteAscendente.setSelected(true);
        jRadioButtonPorNombrePacienteAscendente.setText("Nombre del Paciente (A-Z)");
        jRadioButtonPorNombrePacienteAscendente.setToolTipText("");
        jRadioButtonPorNombrePacienteAscendente.setActionCommand("Nombre del Paciente (A-Z)");
        jRadioButtonPorNombrePacienteAscendente.setName("jRadioButtonPorNombrePacienteAscendente"); // NOI18N
        jRadioButtonPorNombrePacienteAscendente.setOpaque(false);
        jRadioButtonPorNombrePacienteAscendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPorNombrePacienteAscendenteActionPerformed(evt);
            }
        });

        buttonGroupOpcionesOrdenacion.add(jRadioButtonPorAntiguedad);
        jRadioButtonPorAntiguedad.setText("Antigüedad");
        jRadioButtonPorAntiguedad.setToolTipText("");
        jRadioButtonPorAntiguedad.setName("jRadioButtonPorAntiguedad"); // NOI18N
        jRadioButtonPorAntiguedad.setOpaque(false);
        jRadioButtonPorAntiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPorAntiguedadActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Totales por tipo de socio"));

        jLTotalPacientes.setText("TOTAL DE PACIENTES REGISTRADOS");

        jLNumeroPacientesPrivados.setText("Nº de Pacientes Privados:");

        jTFTotalPacientes.setEditable(false);
        jTFTotalPacientes.setBackground(new java.awt.Color(224, 213, 184));
        jTFTotalPacientes.setText(String.valueOf(miGPUI.JFGestionFacturacionPacientesUI.getListaPacientes().size()));
        jTFTotalPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTotalPacientesActionPerformed(evt);
            }
        });

        jTFNumeroPacientesPrivados.setEditable(false);
        jTFNumeroPacientesPrivados.setBackground(new java.awt.Color(224, 213, 184));
        jTFNumeroPacientesPrivados.setText(String.valueOf(miGPUI.PacientePrivado.getNumeroPacientesPrivados()));
        jTFNumeroPacientesPrivados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroPacientesPrivadosActionPerformed(evt);
            }
        });

        jLNumeroPacientesSeguroMedico.setText("Nº de Pacientes con Seguro Médico:");

        jTF_NumeroPacientesSeguroMedico.setEditable(false);
        jTF_NumeroPacientesSeguroMedico.setBackground(new java.awt.Color(224, 213, 184));
        jTF_NumeroPacientesSeguroMedico.setText(String.valueOf(PacienteSeguroMedico.getNumeroPacientesSeguroMedico()));
        jTF_NumeroPacientesSeguroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NumeroPacientesSeguroMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTotalPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLNumeroPacientesPrivados, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTotalPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFNumeroPacientesPrivados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLNumeroPacientesSeguroMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_NumeroPacientesSeguroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(168, 168, 168))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotalPacientes)
                    .addComponent(jTFTotalPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLNumeroPacientesPrivados)
                    .addComponent(jTFNumeroPacientesPrivados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumeroPacientesSeguroMedico)
                    .addComponent(jTF_NumeroPacientesSeguroMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBotonCerrarListado.setMnemonic('C');
        jBotonCerrarListado.setText("Cerrar listado");
        jBotonCerrarListado.setToolTipText("Cerrar listado");
        jBotonCerrarListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCerrarListadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonCerrarListado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButtonPorNombrePacienteAscendente)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPorAntiguedad)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotonMostrar)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOrdenar)
                    .addComponent(jBotonMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPorNombrePacienteAscendente)
                    .addComponent(jRadioButtonPorAntiguedad))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotonCerrarListado)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonCerrarListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCerrarListadoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBotonCerrarListadoActionPerformed

    private void jTFTotalPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTotalPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTotalPacientesActionPerformed

    private void jRadioButtonPorAntiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPorAntiguedadActionPerformed
        int contador ;
        Collections.sort(laLista, new ComparadorAntiguedadPaciente());
        int tamano = laLista.size() ;
        final String vector[] = new String[tamano];
        for (contador = 0; contador < tamano; contador++ ) {
             vector[contador] = laLista.get(contador).getNif() + " -- " + 
                    laLista.get(contador).getNombrePaciente()+" -- " + 
                    laLista.get(contador).getAntiguedad()+" -- " +
                    laLista.get(contador).getEmailNotificaciones()+  
                    String.format(" -- %.2f €.",laLista.get(contador).liquidarFacturacion());
        }

        jListListaPacientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vector ;
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jRadioButtonPorAntiguedadActionPerformed

    private void jRadioButtonPorNombrePacienteAscendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPorNombrePacienteAscendenteActionPerformed

        int contador;
        Collections.sort(laLista, new ComparadorNombrePaciente());
        int tamano = laLista.size() ;
        final String vector[] = new String[tamano];
        for (contador = 0; contador < tamano; contador++ ) {
             vector[contador] = laLista.get(contador).getNif() + " -- " + 
                    laLista.get(contador).getNombrePaciente()+" -- " + 
                    laLista.get(contador).getAntiguedad()+" -- " +
                    laLista.get(contador).getEmailNotificaciones()+  
                    String.format(" -- %.2f €.",laLista.get(contador).liquidarFacturacion());
        }

        jListListaPacientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = vector ;
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jRadioButtonPorNombrePacienteAscendenteActionPerformed

    private void jBotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMostrarActionPerformed

        int indice = jListListaPacientes.getSelectedIndex();
        // Si hay algún elemento seleccionado
        if (indice >=0) {
            PacientePrivado pacientePrivado = (PacientePrivado) laLista.get(indice) ;
            // Mostrar información
            JOptionPane.showMessageDialog(null, pacientePrivado.toString(), "Datos del paciente privado", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(null, "No hay ningún paciente seleccionado.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jBotonMostrarActionPerformed

    private void jTF_NumeroPacientesSeguroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NumeroPacientesSeguroMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NumeroPacientesSeguroMedicoActionPerformed

    private void jTFNumeroPacientesPrivadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroPacientesPrivadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroPacientesPrivadosActionPerformed

    
   
    
    // Ruta y nombre del fichero donde se guardan los clientes de la aplicación
    //private final static String rutayFichero = "C:\\Cliente.dat" ;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOpcionesOrdenacion;
    private javax.swing.JButton jBotonCerrarListado;
    private javax.swing.JButton jBotonMostrar;
    private javax.swing.JLabel jLNumeroPacientesPrivados;
    private javax.swing.JLabel jLNumeroPacientesSeguroMedico;
    private javax.swing.JLabel jLTotalPacientes;
    private javax.swing.JLabel jLabelOrdenar;
    private javax.swing.JList jListListaPacientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonPorAntiguedad;
    private javax.swing.JRadioButton jRadioButtonPorNombrePacienteAscendente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNumeroPacientesPrivados;
    private javax.swing.JTextField jTFTotalPacientes;
    private javax.swing.JTextField jTF_NumeroPacientesSeguroMedico;
    // End of variables declaration//GEN-END:variables
}
